package com.defensoria.proyecto1.entity;
// Generated Mar 13, 2018 1:33:41 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cargos generated by hbm2java
 */
@Entity
@Table(name = "cargos", catalog = "bddefensoriapublica")
public class Cargos implements java.io.Serializable {

	private int idCargos;
	private String cargo;

	public Cargos() {
	}

	public Cargos(int idCargos, String cargo) {
		this.idCargos = idCargos;
		this.cargo = cargo;
	}

	@Id

	@Column(name = "idCargos", unique = true, nullable = false)
	public int getIdCargos() {
		return this.idCargos;
	}

	public void setIdCargos(int idCargos) {
		this.idCargos = idCargos;
	}

	@Column(name = "cargo", nullable = false, length = 3)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

}
